apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-todo
  labels:
    app: spring-todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-todo
  template:
    metadata:
      labels:
        app: spring-todo
    spec:
      containers:
      - name: spring-todo
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
