apiVersion: v1
kind: Service
metadata:
  name: spring-demo-service
  labels:
    app: spring-todo
spec:
  type: LoadBalancer
  selector:
    app: spring-todo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
 
